name: Publish

on:
  push:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: get pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.14.0
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: pnpm
      - name: Upgrade JS dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: pnpm
      - name: Install JS dependencies and build
        run: |
          pnpm install && pnpm build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: audio-bible-player
          directory: dist # e.g. 'dist'
          # automatically provided by ga
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
